version: '3.4'

services:
  angularwithdocker:
    image: ${DOCKER_REGISTRY-}angularwithdocker
    build:
      context: .
      dockerfile: AngularWithDocker/Dockerfile
    ports:
      - "5000:80"
  acceptancetests:
    image: ${DOCKER_REGISTRY-}acceptancetests
    depends_on:
      - "angularwithdocker"
    build:
      context: .
      dockerfile: AcceptanceTests/Dockerfile
